AccessModifierIndentation:
  EnforcedStyle: outdent

AlignParameters:
  EnforcedStyle: with_fixed_indentation

CollectionMethods:
  PreferredMethods:
    inject: 'reduce'

DotPosition:
  EnforcedStyle: trailing

FormatString:
  EnforcedStyle: percent

LambdaCall:
  EnforcedStyle: braces

LineLength:
  Max: 87

PredicateName:
  NamePrefixBlacklist:
    - is_
    - are_

SignalException:
  EnforcedStyle: only_raise
