---
ABS_HYDROGEN_FROM_GAP:
  k: 3e5
  Ea: 35e3
  Tp: 0

ADS_METHYL_TO_111:
  k: 1.2e9
  Ea: 0
  Tp: 0

ADS_METHYL_TO_DIMER:
  k: 1e13
  Ea: 0
  Tp: 0

BRIDGE_WITH_DIMER_TO_HIGH_BRIDGE_AND_DIMER:
  k: 4.2e8
  Ea: 14.9e3
  Tp: 0

DES_METHYL_FROM_111:
  k: 5.4e13
  Ea: 0
  Tp: 0

DES_METHYL_FROM_BRIDGE:
  k: 1.7e14
  Ea: 0
  Tp: 0

DES_METHYL_FROM_DIMER:
  k: 5.3e12
  Ea: 0
  Tp: 0

DIMER_DROP:
  k: 2.2e3
  Ea: 0.8e3
  Tp: 0

DIMER_DROP_AT_END:
  k: 2.2e3
  Ea: 1e3
  Tp: 0

DIMER_DROP_IN_MIDDLE:
  k: 2.2e3
  Ea: 1.2e3
  Tp: 0

DIMER_DROP_NEAR_BRIDGE:
  k: 1.2e8
  Ea: 4e3
  Tp: 0

DIMER_FORMATION:
  k: 8.9e8
  Ea: 0.8e3
  Tp: 0

DIMER_FORMATION_AT_END:
  k: 8.9e8
  Ea: 0.4e3
  Tp: 0

DIMER_FORMATION_IN_MIDDLE:
  k: 8.9e8
  Ea: 0
  Tp: 0

DIMER_FORMATION_NEAR_BRIDGE:
  k: 7.5e8
  Ea: 4e3
  Tp: 0

FORM_TWO_BOND: # imagine
  k: 0
  Ea: 0
  Tp: 0

HIGH_BRIDGE_STAND_TO_DIMER:
  k: 2.2e9
  Ea: 14.9e3
  Tp: 0

HIGH_BRIDGE_STAND_TO_ONE_BRIDGE:
  k: 6.1e13
  Ea: 36.3e3
  Tp: 0

HIGH_BRIDGE_TO_METHYL:
  k: 2.7e8
  Ea: 2.9e3
  Tp: 0

HIGH_BRIDGE_STAND_TO_TWO_BRIDGES:
  k: 2.9e11
  Ea: 3.2e3
  Tp: 0

METHYL_ON_DIMER_ACTIVATION:
  k: 2.8e8
  Ea: 37.5e3
  Tp: 3.5

METHYL_ON_DIMER_DEACTIVATION:
  k: 4.5e13
  Ea: 0
  Tp: 0

METHYL_ON_DIMER_HYDROGEN_MIGRATION:
  k: 2.1e12
  Ea: 37.5e3
  Tp: 0

METHYL_TO_HIGH_BRIDGE:
  k: 9.8e9
  Ea: 15.3e3
  Tp: 0

MIGRATION_DOWN_AT_DIMER: # imagine
  k: 1e8
  Ea: 0
  Tp: 0

MIGRATION_DOWN_AT_DIMER_FROM_111: # imagine
  k: 1e8
  Ea: 0
  Tp: 0

MIGRATION_DOWN_AT_DIMER_FROM_DIMER: # imagine
  k: 0
  Ea: 0
  Tp: 0

MIGRATION_DOWN_AT_DIMER_FROM_HIGH_BRIDGE: # imagine
  k: 1e8
  Ea: 0
  Tp: 0

MIGRATION_DOWN_IN_GAP: # imagine
  k: 1e7
  Ea: 0
  Tp: 0

MIGRATION_DOWN_IN_GAP_FROM_111: # imagine
  k: 1e7
  Ea: 0
  Tp: 0

MIGRATION_DOWN_IN_GAP_FROM_DIMER: # imagine
  k: 0
  Ea: 0
  Tp: 0

MIGRATION_DOWN_IN_GAP_FROM_HIGH_BRIDGE: # imagine
  k: 1e7
  Ea: 0
  Tp: 0

MIGRATION_THROUGH_DIMERS_ROW:
  k: 2.4e8
  Ea: 16e3
  Tp: 0

NEXT_LEVEL_BRIDGE_TO_HIGH_BRIDGE:
  k: 1.1e12
  Ea: 12.3e3
  Tp: 0

SIERPINSKI_DROP:
  k: 4.4e9
  Ea: 14e3
  Tp: 0

SURFACE_ACTIVATION:
  k: 5.2e13
  Ea: 6.65e3
  Tp: 0

SURFACE_DEACTIVATION:
  k: 2e13
  Ea: 0
  Tp: 0

TWO_BRIDGES_TO_HIGH_BRIDGE:
  k: 1.1e8
  Ea: 3.2e3
  Tp: 0
