---
ABS_HYDROGEN_FROM_GAP:
  A: 3e5
  Ea: 35e3
  Tp: 0

ADS_METHYL_TO_111:
  A: 1.2e9
  Ea: 0
  Tp: 0

ADS_METHYL_TO_DIMER:
  A: 1e13
  Ea: 0
  Tp: 0

BRIDGE_WITH_DIMER_TO_HIGH_BRIDGE_AND_DIMER:
  A: 4.2e8
  Ea: 14.9e3
  Tp: 0

DES_METHYL_FROM_111:
  A: 5.4e6
  Ea: 0
  Tp: 0

DES_METHYL_FROM_BRIDGE:
  A: 1.7e7
  Ea: 0
  Tp: 0

DES_METHYL_FROM_DIMER:
  A: 5.3e3
  Ea: 0
  Tp: 0

DIMER_DROP:
  A: 2.2e3
  Ea: 0.8e3
  Tp: 0

DIMER_DROP_AT_END:
  A: 2.2e3
  Ea: 1e3
  Tp: 0

DIMER_DROP_IN_MIDDLE:
  A: 2.2e3
  Ea: 1.2e3
  Tp: 0

DIMER_DROP_NEAR_BRIDGE:
  A: 1.2e8
  Ea: 4e3
  Tp: 0

DIMER_FORMATION:
  A: 8.9e8
  Ea: 0.8e3
  Tp: 0

DIMER_FORMATION_AT_END:
  A: 8.9e8
  Ea: 0.4e3
  Tp: 0

DIMER_FORMATION_IN_MIDDLE:
  A: 8.9e8
  Ea: 0
  Tp: 0

DIMER_FORMATION_NEAR_BRIDGE:
  A: 7.5e8
  Ea: 4e3
  Tp: 0

FORM_TWO_BOND: # imagine
  A: 1e7
  Ea: 0
  Tp: 0

HIGH_BRIDGE_STAND_TO_DIMER:
  A: 2.2e9
  Ea: 14.9e3
  Tp: 0

HIGH_BRIDGE_STAND_TO_ONE_BRIDGE:
  A: 6.1e13
  Ea: 36.3e3
  Tp: 0

HIGH_BRIDGE_TO_METHYL:
  A: 2.7e7
  Ea: 2.9e3
  Tp: 0

HIGH_BRIDGE_STAND_TO_TWO_BRIDGES:
  A: 2.9e11
  Ea: 3.2e3
  Tp: 0

METHYL_ON_DIMER_ACTIVATION:
  A: 2.8e8
  Ea: 37.5e3
  Tp: 3.5

METHYL_ON_DIMER_DEACTIVATION:
  A: 4.5e13
  Ea: 0
  Tp: 0

METHYL_ON_DIMER_HYDROGEN_MIGRATION:
  A: 2.1e12
  Ea: 37.5e3
  Tp: 0

METHYL_TO_HIGH_BRIDGE:
  A: 9.8e8
  Ea: 15.3e3
  Tp: 0

MIGRATION_DOWN_AT_DIMER: # imagine
  A: 1e2
  Ea: 0
  Tp: 0

MIGRATION_DOWN_AT_DIMER_FROM_111: # imagine
  A: 0
  Ea: 0
  Tp: 0

MIGRATION_DOWN_AT_DIMER_FROM_DIMER: # imagine
  A: 0
  Ea: 0
  Tp: 0

MIGRATION_DOWN_AT_DIMER_FROM_HIGH_BRIDGE: # imagine
  A: 0
  Ea: 0
  Tp: 0

MIGRATION_DOWN_IN_GAP: # imagine
  A: 1e7
  Ea: 0
  Tp: 0

MIGRATION_DOWN_IN_GAP_FROM_111: # imagine
  A: 0
  Ea: 0
  Tp: 0

MIGRATION_DOWN_IN_GAP_FROM_DIMER: # imagine
  A: 0
  Ea: 0
  Tp: 0

MIGRATION_DOWN_IN_GAP_FROM_HIGH_BRIDGE: # imagine
  A: 0
  Ea: 0
  Tp: 0

MIGRATION_THROUGH_DIMERS_ROW:
  A: 2.4e8
  Ea: 30e3
  Tp: 0

NEXT_LEVEL_BRIDGE_TO_HIGH_BRIDGE:
  A: 1.1e12
  Ea: 12.3e3
  Tp: 0

SIERPINSKI_DROP:
  A: 4.4e9
  Ea: 30e3
  Tp: 0

SURFACE_ACTIVATION:
  A: 5.2e13
  Ea: 6.65e3
  Tp: 0

SURFACE_DEACTIVATION:
  A: 2e13
  Ea: 0
  Tp: 0

TWO_BRIDGES_TO_HIGH_BRIDGE:
  A: 1.1e8
  Ea: 3.2e3
  Tp: 0
