---
system:
  size_x: 15
  size_y: 15
  behavior: tor
  time: 0.003

progress:
  step: 0.0001

integral:
  step: 0.0005
  atom_types: [0, 2, 4, 5, 20, 21, 24, 28, 32]

mol:
  step: 0.001
  detector: all

xyz:
  step: 0.0007
  detector: surf
