MIRROR = {
  'abs hydrogen from gap': 'forward hydrogen abstraction from gap',
  'adsorption methyl to 111': 'forward methyl adsorption to face 111',
  'adsorption methyl to dimer': 'forward adsorption methyl to dimer',
  'bridge with dimer to high bridge and dimer': 'reverse high bridge stand to dimer',
  'desorption methyl from 111': 'forward desorption methyl from 111',
  'desorption methyl from bridge': 'forward desorption methyl from bridge',
  'desorption methyl from dimer': 'forward desorption methyl from dimer',
  'desorption methyl from dimer': 'forward desorption methyl from dimer',
  'dimer drop at end of dimers row': 'reverse dimer formation at end of dimers row',
  'dimer drop in middle of dimers row': 'reverse dimer formation in middle of dimers row',
  'dimer drop near bridge': 'reverse dimer formation near bridge',
  'dimer drop': 'reverse dimer formation not in dimers row',
  'dimer formation at end of dimers row': 'forward dimer formation at end of dimers row',
  'dimer formation in middle of dimers row': 'forward dimer formation in middle of dimers row',
  'dimer formation near bridge': 'forward dimer formation near bridge',
  'dimer formation': 'forward dimer formation not in dimers row',
  'high bridge incorporates in crystal lattice near another bridge': 'forward high bridge incorporates in crystal lattice near another bridge',
  'high bridge stand to bridge at new level': 'forward high bridge stand to bridge at new level',
  'high bridge stand to dimer': 'forward high bridge stand to dimer',
  'high bridge to methyl': 'reverse methyl to high bridge',
  'methyl on dimer activation': 'forward methyl on dimer activation',
  'methyl on dimer deactivation': 'forward methyl on dimer deactivation',
  'methyl on dimer hydrogen migration': 'forward methyl on dimer hydrogen migration',
  'methyl to high bridge': 'forward methyl to high bridge',
  'migration down at activated dimer from high bridge': 'forward migration down at activated dimer from high bridge',
  'migration down at activated dimer from methyl on bridge': 'forward migration down at activated dimer from methyl on bridge',
  'migration down in gap from high bridge': 'forward migration down in gap from high bridge',
  'migration down in gap from methyl on bridge': 'forward migration down in gap from bridge',
  'migration through dimers row': 'forward migration through dimers row',
  'next layer bridge to high bridge': 'reverse high bridge stand to bridge at new level',
  'sierpinski drop': 'forward sierpinski drop',
  'surface activation': 'forward surface activation',
  'surface deactivation': 'forward surface deactivation',
  'two bridges to high bridge': 'reverse high bridge incorporates in crystal lattice near another bridge'
}

def convert(freq_stat):
  return dict([(MIRROR[k], v) for k, v in freq_stat.items()])
