NAME		:= vd_engine

CXX		:= <%= CC %>
CXXFLAGS	:= <%= FLAGS %>

ENGINE_DIR	:= <%= ENGINE_DIR %>
RESULTS_DIR	:= <%= RESULTS_DIR %>
OBJS_DIR	:= <%= OBJS_DIR %>

OBJECTS_DIRS	:= <%= objects_dirs %>
HEADER_FILES	:= <%= header_files %>
SOURCE_FILES	:= <%= source_files %>
SOURCE_OBJECTS	:= $(SOURCE_FILES:%.cpp=%.o)

###################

define compilate_obj
$(if $(findstring $(RESULTS_DIR), $(1)), \
	$(CXX) $(CXXFLAGS) -o $(patsubst $(RESULTS_DIR)/%, $(OBJS_DIR)/%, $(1)) -c $(2), \
	$(CXX) $(CXXFLAGS) -o $(patsubst $(ENGINE_DIR)/%, $(OBJS_DIR)/%, $(1)) -c $(2))
endef

###################

all:	$(NAME)
$(NAME):	obj_dirs $(SOURCE_OBJECTS)

obj_dirs:
	mkdir -p $(OBJECTS_DIRS)

.h.o:
	$(call compilate_obj, $@, $<)

.cpp.o:	$(HEADER_FILES)
	$(call compilate_obj, $@, $<)

clean:
	rm -rf $(OBJS_DIR)
